# This is a basic workflow to help you get started with Actions

name: label test


# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types: [closed]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.github_token }}
          labels: documentation
          number: ${{ github.context.issue.number }}
